<?php
include("Object.php");
include("WHException.php");
include("WHMultipleInheritance.php");
include("WHAssociation.php");
include("WHError.php");
include("WHErrorHandler.php");
include("WHDate.php");
include("WHTime.php");
include("WHDateAndTime.php");
include('WHDuration.php');
include('WHProxyObjectLogCall.php');
include('WHScopeBreak.php');
include('WHReflectionClass.php');